/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\models\nice.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/nice.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0.184, 0.412, -3.126]} rotation={[-Math.PI, 0.248, -Math.PI]} scale={[2.071, 2.18, 1.654]}>
        </group>
        <group name="Plane" scale={[9.296, 8.009, 9.634]}>
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.Default} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.laminate} />
        </group>
        <mesh name="Dumbbell" geometry={nodes.Dumbbell.geometry} material={materials['Material.011']} position={[4.615, 0.143, -3.706]} rotation={[-0.047, 1.194, 0.048]} />
        <mesh name="Dumbbell001" geometry={nodes.Dumbbell001.geometry} material={materials['Material.013']} position={[3.589, 0.163, -4.369]} rotation={[-2.458, 0.786, 2.566]} />
        <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={materials.white} position={[1.052, 2.108, -4.095]} rotation={[-0.053, 0.154, 0.168]} scale={[0.979, 2.717, 0.985]} />
        <mesh name="Mousepad" geometry={nodes.Mousepad.geometry} material={materials.Mousepad} position={[1.152, 2.101, -4.427]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.709, 0.419, 1]} />
        <group name="hylly" position={[-4.426, 3.708, -5.296]} rotation={[0, -1.565, 0]}>
          <mesh name="Cube-Mesh" geometry={nodes['Cube-Mesh'].geometry} material={materials.Top} />
          <mesh name="Cube-Mesh_1" geometry={nodes['Cube-Mesh_1'].geometry} material={materials.Supports} />
        </group>
        <mesh name="iMac" geometry={nodes.iMac.geometry} material={materials.Screen} position={[0, 2.088, -5.258]} rotation={[Math.PI, -1.549, Math.PI]} />
        <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={materials['Mat.001']} position={[0.089, 2.135, -4.374]} />
        <group name="Kukka" position={[-2.028, 2.401, -5.326]}>
          <mesh name="mesh1885116500" geometry={nodes.mesh1885116500.geometry} material={materials['mat21.002']} />
          <mesh name="mesh1885116500_1" geometry={nodes.mesh1885116500_1.geometry} material={materials['mat20.001']} />
          <mesh name="mesh1885116500_2" geometry={nodes.mesh1885116500_2.geometry} material={materials.white} />
          <mesh name="mesh1885116500_3" geometry={nodes.mesh1885116500_3.geometry} material={materials.black} />
          <mesh name="mesh1885116500_4" geometry={nodes.mesh1885116500_4.geometry} material={materials.mat9} />
        </group>
        <group name="Node" position={[-5.767, 4.71, 3.091]}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.mat10} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat23} />
          <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat21} />
          <mesh name="Node-Mesh_3" geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat4} />
          <mesh name="Node-Mesh_4" geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat8} />
          <mesh name="Node-Mesh_5" geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat5} />
          <mesh name="Node-Mesh_6" geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat3} />
          <mesh name="Node-Mesh_7" geometry={nodes['Node-Mesh_7'].geometry} material={materials['mat17.001']} />
          <mesh name="Node-Mesh_8" geometry={nodes['Node-Mesh_8'].geometry} material={materials.mat16} />
          <mesh name="Node-Mesh_9" geometry={nodes['Node-Mesh_9'].geometry} material={materials.mat1} />
        </group>
        <mesh name="Books" geometry={nodes.Books.geometry} material={materials['Material.003']} position={[-5.761, 2.327, 3.495]} rotation={[0, 1.499, 0]} />
        <mesh name="Bookshelf" geometry={nodes.Bookshelf.geometry} material={materials.black} position={[-5.818, 0.119, 2.754]} rotation={[0, 1.565, 0]} />
        <group name="pyota" position={[0, 0.162, -4.836]} rotation={[0, -1.562, 0]}>
          <mesh name="Cube004_Cube005_BlackCoatSteel" geometry={nodes.Cube004_Cube005_BlackCoatSteel.geometry} material={materials.BlackCoatSteel} />
          <mesh name="Cube004_Cube005_BlackCoatSteel_1" geometry={nodes.Cube004_Cube005_BlackCoatSteel_1.geometry} material={materials.GrayPlastic} />
          <mesh name="Cube004_Cube005_BlackCoatSteel_2" geometry={nodes.Cube004_Cube005_BlackCoatSteel_2.geometry} material={materials.WhiteSteelScrew} />
          <mesh name="Cube004_Cube005_BlackCoatSteel_3" geometry={nodes.Cube004_Cube005_BlackCoatSteel_3.geometry} material={materials.BlackPlastic} />
          <mesh name="Cube004_Cube005_BlackCoatSteel_4" geometry={nodes.Cube004_Cube005_BlackCoatSteel_4.geometry} material={materials.BlackWood} />
        </group>
        <mesh name="Trophy" geometry={nodes.Trophy.geometry} material={materials['Material.005']} position={[-5.04, 4.006, -5.187]} />
        <group name="Trophy_Cube001" position={[-3.792, 3.988, -5.52]} rotation={[0, -1.463, 0]}>
          <mesh name="Trophy_Cube024_1001" geometry={nodes.Trophy_Cube024_1001.geometry} material={materials['FFEB3B.001']} />
          <mesh name="Trophy_Cube024_1001_1" geometry={nodes.Trophy_Cube024_1001_1.geometry} material={materials['1A1A1A.001']} />
          <mesh name="Trophy_Cube024_1001_2" geometry={nodes.Trophy_Cube024_1001_2.geometry} material={materials['F44336.001']} />
        </group>
        <group name="OfficeChair" position={[0.056, 0.19, -3.18]} rotation={[-Math.PI / 2, 0, 2.824]} scale={[0.984, 0.839, 1.073]}>
          <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
          <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
          <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
        </group>
        <mesh name="Rug" geometry={nodes.Rug.geometry} material={materials.Screen} position={[-0.173, 0.076, 1.271]} />
        <mesh name="Books002" geometry={nodes.Books002.geometry} material={materials['Material.014']} position={[-5.621, 1.338, 4.158]} rotation={[0, 1.499, 0]} />
        <group name="Node001" position={[-5.85, 3.626, 2.406]}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials['mat10.002']} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['mat23.003']} />
          <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={materials['mat21.004']} />
          <mesh name="Node-Mesh001_3" geometry={nodes['Node-Mesh001_3'].geometry} material={materials['mat4.002']} />
          <mesh name="Node-Mesh001_4" geometry={nodes['Node-Mesh001_4'].geometry} material={materials['mat8.002']} />
          <mesh name="Node-Mesh001_5" geometry={nodes['Node-Mesh001_5'].geometry} material={materials['mat5.002']} />
          <mesh name="Node-Mesh001_6" geometry={nodes['Node-Mesh001_6'].geometry} material={materials['mat3.002']} />
          <mesh name="Node-Mesh001_7" geometry={nodes['Node-Mesh001_7'].geometry} material={materials['mat17.004']} />
          <mesh name="Node-Mesh001_8" geometry={nodes['Node-Mesh001_8'].geometry} material={materials['mat16.002']} />
          <mesh name="Node-Mesh001_9" geometry={nodes['Node-Mesh001_9'].geometry} material={materials['mat1.002']} />
        </group>
        <mesh name="Screen" geometry={nodes.Screen.geometry} material={materials.Screen} position={[0, 2.088, -5.258]} rotation={[Math.PI, -1.549, Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/nice.gltf')
