/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\public\models\MySpace.gltf 
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture, useVideoTexture} from '@react-three/drei'
import {motion} from 'framer-motion-3d'
import { useFrame } from "@react-three/fiber";
import { animate, useMotionValue } from "framer-motion";
import * as THREE from 'three'

export function MySpace(props) {
  const {section} = props
  const { nodes, materials } = useGLTF('models/nice.gltf')
  const texture = useTexture("textures/baked.jpg")
  const textureVSCode = useVideoTexture("textures/vscode.mp4");


  texture.flipY = false
  texture.colorSpace = THREE.SRGBColorSpace;


  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent:true,
    opacity:1
  })
  const textureOpacity = useMotionValue(0);
  useEffect(() => {

    animate(textureOpacity, section === 0 ? 1 : 0, {duration: 0.8})
  }, [section]);

  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
  });
  return (
    <group {...props} dispose={null}>
    <mesh name="Screen" 
    geometry={nodes.Screen.geometry} 
    material={materials.Screen} 
    position={[0, 2.088, -5.258]} 
    rotation={[Math.PI, -1.549, Math.PI]} >
    <meshBasicMaterial map={textureVSCode} toneMapped={false} />
   </mesh>

    <group name="Plane" scale={[9.296, 8.009, 9.634]}>
      <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial} />
      <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={textureMaterial} />
    </group>
    <motion.mesh 
       initial={{
        scale: [0, 0, 0]
      }}
     animate={{
       scale: section === 0 ? 1 : 0,
     }}name="Dumbbell" geometry={nodes.Dumbbell.geometry} material={textureMaterial} position={[4.615, 0.143, -3.706]} rotation={[-0.047, 1.194, 0.048]} />
    <motion.mesh 
     scale={[0, 0, 0]}
     animate={{
       scale: section === 0 ? 1 : 0,
     }}name="Dumbbell001" geometry={nodes.Dumbbell001.geometry} material={textureMaterial} position={[3.589, 0.163, -4.369]} rotation={[-2.458, 0.786, 2.566]} />
    <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={textureMaterial} position={[1.000, 2.108, -4.284]} rotation={[-0.053, 0.154, 0.168]} scale={[1.030, 2.459, 0.945]}  />
    <mesh name="Mousepad" geometry={nodes.Mousepad.geometry} material={textureMaterial} position={[1.152, 2.101, -4.427]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.709, 0.419, 1]} />
    <motion.group 
    scale={[0, 0, 0]}
    animate={{
      scale: section === 0 ? 1 : 0,
    }}
    name="hylly" position={[-4.426, 3.708, -5.296]} rotation={[0, -1.565, 0]}>
      <mesh name="Cube-Mesh" geometry={nodes['Cube-Mesh'].geometry} material={textureMaterial} />
      <mesh name="Cube-Mesh_1" geometry={nodes['Cube-Mesh_1'].geometry} material={textureMaterial} />
    </motion.group>
    
    <motion.mesh
    scale={[0, 0, 0]}
    animate={{
     scale: section === 0 ? 1 : 0,
    }} name="iMac" geometry={nodes.iMac.geometry} material={textureMaterial} position={[0, 2.088, -5.258]} rotation={[Math.PI, -1.549, Math.PI]} />
    <motion.mesh
    scale={[0, 0, 0]}
    animate={{
     scale: section === 0 ? 1 : 0,
    }}
     name="Keyboard" geometry={nodes.Keyboard.geometry} material={textureMaterial} position={[0.300, 2.138, -4.374]} />
    <motion.group 
       initial={{
    scale: [0, 0, 0]
  }}
     animate={{
      scale: section === 0 ? 1 : 0,
     }}
     name="Kukka" position={[-2.028, 2.401, -5.326]}>
      <mesh name="mesh1885116500" geometry={nodes.mesh1885116500.geometry} material={textureMaterial} />
      <mesh name="mesh1885116500_1" geometry={nodes.mesh1885116500_1.geometry} material={textureMaterial} />
      <mesh name="mesh1885116500_2" geometry={nodes.mesh1885116500_2.geometry} material={textureMaterial} />
      <mesh name="mesh1885116500_3" geometry={nodes.mesh1885116500_3.geometry} material={textureMaterial} />
      <mesh name="mesh1885116500_4" geometry={nodes.mesh1885116500_4.geometry} material={textureMaterial} />
    </motion.group>
    <motion.group 
     scale={[0, 0, 0]}
     animate={{
      scale: section === 0 ? 1 : 0,
     }}
     name="Node" position={[-5.767, 4.71, 3.091]}>
      <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_3" geometry={nodes['Node-Mesh_3'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_4" geometry={nodes['Node-Mesh_4'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_5" geometry={nodes['Node-Mesh_5'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_6" geometry={nodes['Node-Mesh_6'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_7" geometry={nodes['Node-Mesh_7'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_8" geometry={nodes['Node-Mesh_8'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh_9" geometry={nodes['Node-Mesh_9'].geometry} material={textureMaterial} />
    </motion.group>
    <motion.mesh scale={[0, 0, 0]}
     animate={{
      scale: section === 0 ? 1 : 0,
     }}
     name="Books" geometry={nodes.Books.geometry} material={textureMaterial} position={[-5.761, 2.327, 3.495]} rotation={[0, 1.499, 0]} />
    <mesh name="Bookshelf" geometry={nodes.Bookshelf.geometry} material={textureMaterial} position={[-5.818, 0.119, 2.754]} rotation={[0, 1.565, 0]} />
    <group name="pyota" position={[0, 0.162, -4.836]} rotation={[0, -1.562, 0]}>
      <mesh name="Cube004_Cube005_BlackCoatSteel" geometry={nodes.Cube004_Cube005_BlackCoatSteel.geometry} material={textureMaterial} />
      <mesh name="Cube004_Cube005_BlackCoatSteel_1" geometry={nodes.Cube004_Cube005_BlackCoatSteel_1.geometry} material={textureMaterial} />
      <mesh name="Cube004_Cube005_BlackCoatSteel_2" geometry={nodes.Cube004_Cube005_BlackCoatSteel_2.geometry} material={textureMaterial} />
      <mesh name="Cube004_Cube005_BlackCoatSteel_3" geometry={nodes.Cube004_Cube005_BlackCoatSteel_3.geometry} material={textureMaterial} />
      <mesh name="Cube004_Cube005_BlackCoatSteel_4" geometry={nodes.Cube004_Cube005_BlackCoatSteel_4.geometry} material={textureMaterial} />
    </group>
    <mesh name="Trophy" geometry={nodes.Trophy.geometry} material={textureMaterial} position={[-5.04, 4.006, -5.187]} />
    <group name="Trophy_Cube001" position={[-3.792, 3.988, -5.52]} rotation={[0, -1.463, 0]}>
      <mesh name="Trophy_Cube024_1001" geometry={nodes.Trophy_Cube024_1001.geometry} material={textureMaterial} />
      <mesh name="Trophy_Cube024_1001_1" geometry={nodes.Trophy_Cube024_1001_1.geometry} material={textureMaterial} />
      <mesh name="Trophy_Cube024_1001_2" geometry={nodes.Trophy_Cube024_1001_2.geometry} material={textureMaterial} />
    </group>
    <motion.group 
     scale={[0, 0, 0]}
     animate={{
       scale: section === 0 ? 1 : 0,
     }}
     name="OfficeChair" position={[0.056, 0.19, -3.18]} rotation={[-Math.PI / 2, 0, 2.824]}>
      <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={textureMaterial} />
      <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={textureMaterial} />
      <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={textureMaterial} />
    </motion.group>
    <motion.mesh 
    scale={[0, 0, 0]}
    animate={{
      scale: section === 0 ? 1 : 0,
    }}
    name="Rug" geometry={nodes.Rug.geometry} material={textureMaterial} position={[-0.173, 0.076, 1.271]} />
    <mesh name="Books002" geometry={nodes.Books002.geometry} material={textureMaterial} position={[-5.621, 1.338, 4.158]} rotation={[0, 1.499, 0]} />
    <motion.group
     scale={[0, 0, 0]}
     animate={{
       scale: section === 0 ? 1 : 0,
     }}
     name="Node001" position={[-5.85, 3.626, 2.406]}>
      <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_3" geometry={nodes['Node-Mesh001_3'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_4" geometry={nodes['Node-Mesh001_4'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_5" geometry={nodes['Node-Mesh001_5'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_6" geometry={nodes['Node-Mesh001_6'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_7" geometry={nodes['Node-Mesh001_7'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_8" geometry={nodes['Node-Mesh001_8'].geometry} material={textureMaterial} />
      <mesh name="Node-Mesh001_9" geometry={nodes['Node-Mesh001_9'].geometry} material={textureMaterial} />
    </motion.group>
  </group>
  )
}

useGLTF.preload('models/nice.gltf')
useGLTF.preload('textures/baked.jpg')
